name: Minimal Test
description: Absolute minimal workflow test
version: 1.0

settings:
  useTaskIds: false
  poll_interval: 2
  timeout: 120

stages:
  - id: test
    name: Test
    prompt: "Type: TEST_COMPLETE"
    trigger_keyword: TEST_COMPLETE
    timeout: 60
    on_success:
      - action: complete_workflow