name: Persistent Response Workflow
description: Responds every time a keyword is detected
version: 1.0

settings:
  useTaskIds: false
  poll_interval: 2
  timeout: 60
  bind_to_existing: true  # Don't spawn new instance
  monitor_only: false     # Send prompts to the instance

stages:
  - id: respond_stage
    name: "Respond to Trigger"
    prompt: |
      🔔 TRIGGER_COMMAND detected!
      
      I'll acknowledge this trigger and perform a quick task.
      
      Current time: {{timestamp}}
      Trigger count: {{trigger_count}}
      
      Let me check the current directory and show you I'm responding:
    trigger_keyword: RESPONSE_ACKNOWLEDGED
    timeout: 60
    on_success:
      - action: log
        message: "✅ Response completed at {{timestamp}}"
      - action: send_prompt
        target: current
        prompt: |
          ✅ Task completed! 
          
          I'm ready for the next TRIGGER_COMMAND.
          The monitor will keep watching for more triggers.
      - action: complete_workflow